### ISSUE TITLE
一直报错,提示“Module.yaml.scanner.ScannerError: while scanning a simple key”

### ISSUE THREAD

**Issue by t0ber00t** [Miagz/XrayFofa#4]
![image](https://user-images.githubusercontent.com/14084654/106086731-b6b37880-615d-11eb-872e-df373dc4dde1.png)
Module.yaml.scanner.ScannerError: while scanning a simple key
  in "scan_config.yaml", line 18, column 9
could not find expected ':'
  in "scan_config.yaml", line 20, column 9

**Comment by Miagz** [comment]
> ![image](https://user-images.githubusercontent.com/14084654/106086731-b6b37880-615d-11eb-872e-df373dc4dde1.png)
> Module.yaml.scanner.ScannerError: while scanning a simple key
> in "scan_config.yaml", line 18, column 9
> could not find expected ':'
> in "scan_config.yaml", line 20, column 9

原因很简单呀，scan_config.yaml  中配置出问题了，你key值没有打空格就会造成这样，打空格间隔是yaml的一个规则

**Comment by Miagz** [comment]
> ![image](https://user-images.githubusercontent.com/14084654/106086731-b6b37880-615d-11eb-872e-df373dc4dde1.png)
> Module.yaml.scanner.ScannerError: while scanning a simple key
> in "scan_config.yaml", line 18, column 9
> could not find expected ':'
> in "scan_config.yaml", line 20, column 9

![image](https://user-images.githubusercontent.com/53965781/106750470-da495800-6662-11eb-95ec-155f2f1dc731.png)
我也复现出这个情况了
![image](https://user-images.githubusercontent.com/53965781/106750639-0b298d00-6663-11eb-943f-fa105154ec93.png)
原因就是没有打空格间隔

**Comment by t0ber00t** [comment]
> > ![image](https://user-images.githubusercontent.com/14084654/106086731-b6b37880-615d-11eb-872e-df373dc4dde1.png)
> > Module.yaml.scanner.ScannerError: while scanning a simple key
> > in "scan_config.yaml", line 18, column 9
> > could not find expected ':'
> > in "scan_config.yaml", line 20, column 9
> 
> 原因很简单呀，scan_config.yaml 中配置出问题了，你key值没有打空格就会造成这样，打空格间隔是yaml的一个规则

感谢大佬，就是这个原因，但是新的问题也出现了。。。求指导
![image](https://user-images.githubusercontent.com/14084654/106859434-fc43e880-66fd-11eb-9412-450a45c8f967.png)

![image](https://user-images.githubusercontent.com/14084654/106859358-e2a2a100-66fd-11eb-9bc4-3c00aad4b2d4.png)

**Comment by t0ber00t** [comment]
> > ![image](https://user-images.githubusercontent.com/14084654/106086731-b6b37880-615d-11eb-872e-df373dc4dde1.png)
> > Module.yaml.scanner.ScannerError: while scanning a simple key
> > in "scan_config.yaml", line 18, column 9
> > could not find expected ':'
> > in "scan_config.yaml", line 20, column 9
> 
> ![image](https://user-images.githubusercontent.com/53965781/106750470-da495800-6662-11eb-95ec-155f2f1dc731.png)
> 我也复现出这个情况了
> ![image](https://user-images.githubusercontent.com/53965781/106750639-0b298d00-6663-11eb-943f-fa105154ec93.png)
> 原因就是没有打空格间隔

感谢大佬，就是这个原因，之前的问题解决了，但是新的问题也出现了。。。求指导
![image](https://user-images.githubusercontent.com/14084654/106859434-fc43e880-66fd-11eb-9412-450a45c8f967.png)

![image](https://user-images.githubusercontent.com/14084654/106859358-e2a2a100-66fd-11eb-9bc4-3c00aad4b2d4.png)

**Comment by Miagz** [comment]
> > > ![image](https://user-images.githubusercontent.com/14084654/106086731-b6b37880-615d-11eb-872e-df373dc4dde1.png)
> > > Module.yaml.scanner.ScannerError: while scanning a simple key
> > > in "scan_config.yaml", line 18, column 9
> > > could not find expected ':'
> > > in "scan_config.yaml", line 20, column 9
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/53965781/106750470-da495800-6662-11eb-95ec-155f2f1dc731.png)
> > 我也复现出这个情况了
> > ![image](https://user-images.githubusercontent.com/53965781/106750639-0b298d00-6663-11eb-943f-fa105154ec93.png)
> > 原因就是没有打空格间隔
> 
> 感谢大佬，就是这个原因，之前的问题解决了，但是新的问题也出现了。。。求指导
> ![image](https://user-images.githubusercontent.com/14084654/106859434-fc43e880-66fd-11eb-9412-450a45c8f967.png)
> 
> ![image](https://user-images.githubusercontent.com/14084654/106859358-e2a2a100-66fd-11eb-9bc4-3c00aad4b2d4.png)

这个好像是因为fofa语法方面出的问题，是domain处的语法出了点问题吧，具体的我也不清楚，我复现了好几回就复现出一次你那种情况，但继续跑时有正常运行了

**Comment by Stowaway-y** [comment]
domain的语法不对吗？我也出现这个问题了啊
 File "scan.py", line 72, in Fofa
    for host in search.get_data('%s'%(value),count)['results']:
KeyError: 'results'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "scan.py", line 113, in run
    urllist = self.Fofa(count)
  File "scan.py", line 72, in Fofa
    for host in search.get_data('%s'%(value),count)['results']:
KeyError: 'results'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "scan.py", line 113, in run
    urllist = self.Fofa(count)
  File "scan.py", line 72, in Fofa
    for host in search.get_data('%s'%(value),count)['results']:
KeyError: 'results'
这个解决了么？

**Comment by xz00311** [comment]
fofa官网一直找不到
