### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by gusechuisheng** [Miagz/XrayFofa#7]
python7 配置完运行报错怎么解决啊

Traceback (most recent call last):
  File "scan.py", line 138, in <module>
    scan_config = Module.yaml.full_load(open('scan_config.yaml','rb'))
  File "D:\sectools\信息收集\XrayFofa\Module\yaml\__init__.py", line 142, in full_load
    return load(stream, FullLoader)
  File "D:\sectools\信息收集\XrayFofa\Module\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "D:\sectools\信息收集\XrayFofa\Module\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "D:\sectools\信息收集\XrayFofa\Module\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "D:\sectools\信息收集\XrayFofa\Module\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "D:\sectools\信息收集\XrayFofa\Module\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "D:\sectools\信息收集\XrayFofa\Module\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "D:\sectools\信息收集\XrayFofa\Module\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "D:\sectools\信息收集\XrayFofa\Module\yaml\parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
Module.yaml.parser.ParserError: while parsing a block mapping
  in "scan_config.yaml", line 2, column 1
expected <block end>, but found '<scalar>'
  in "scan_config.yaml", line 7, column 9

**Comment by Miagz** [comment]
> python7 配置完运行报错怎么解决啊
> 
> Traceback (most recent call last):
> File "scan.py", line 138, in
> scan_config = Module.yaml.full_load(open('scan_config.yaml','rb'))
> File "D:\sectools\信息收集\XrayFofa\Module\yaml__init__.py", line 142, in full_load
> return load(stream, FullLoader)
> File "D:\sectools\信息收集\XrayFofa\Module\yaml__init__.py", line 114, in load
> return loader.get_single_data()
> File "D:\sectools\信息收集\XrayFofa\Module\yaml\constructor.py", line 49, in get_single_data
> node = self.get_single_node()
> File "D:\sectools\信息收集\XrayFofa\Module\yaml\composer.py", line 36, in get_single_node
> document = self.compose_document()
> File "D:\sectools\信息收集\XrayFofa\Module\yaml\composer.py", line 55, in compose_document
> node = self.compose_node(None, None)
> File "D:\sectools\信息收集\XrayFofa\Module\yaml\composer.py", line 84, in compose_node
> node = self.compose_mapping_node(anchor)
> File "D:\sectools\信息收集\XrayFofa\Module\yaml\composer.py", line 127, in compose_mapping_node
> while not self.check_event(MappingEndEvent):
> File "D:\sectools\信息收集\XrayFofa\Module\yaml\parser.py", line 98, in check_event
> self.current_event = self.state()
> File "D:\sectools\信息收集\XrayFofa\Module\yaml\parser.py", line 438, in parse_block_mapping_key
> raise ParserError("while parsing a block mapping", self.marks[-1],
> Module.yaml.parser.ParserError: while parsing a block mapping
> in "scan_config.yaml", line 2, column 1
> expected , but found ''
> in "scan_config.yaml", line 7, column 9

加我私聊下吧 848327421
